import 'package:Inspection/pages/packer/models/packer_model.dart';
import 'package:sqflite/sqflite.dart';

final String tablePacker = 'TABLE_PACKER';

Future packerTable(Database db) async {
  final idType = 'integer primary key autoincrement';
  final boolType = 'integer not null';
  final textType = 'text not null';

  db.execute('''
    create table $tablePacker(
       ${PackerFields.id} $idType,
       ${PackerFields.userName} $textType,
       ${PackerFields.idUser} $textType,
       ${PackerFields.shift} $textType,
       ${PackerFields.time} $textType,

          ${PackerFields.sg011} $boolType,
          ${PackerFields.pg011} $boolType,
          ${PackerFields.as011} $boolType,
          ${PackerFields.as021} $boolType,
          ${PackerFields.bl1} $boolType,
          ${PackerFields.be01611} $boolType,
          ${PackerFields.as031} $boolType,
          ${PackerFields.pg021} $boolType,
          ${PackerFields.pg031} $boolType,
          ${PackerFields.bf1} $boolType,
          ${PackerFields.vs011} $boolType,
          ${PackerFields.be01661} $boolType,
          ${PackerFields.sc011} $boolType,
          ${PackerFields.bb1} $boolType,
          ${PackerFields.asb1} $boolType,
          ${PackerFields.la1} $boolType,
          ${PackerFields.b3b1} $boolType,
          ${PackerFields.bf011} $boolType,
          ${PackerFields.rf011} $boolType,
          ${PackerFields.sc031} $boolType,
          ${PackerFields.sc041} $boolType,
          ${PackerFields.as041} $boolType,
          ${PackerFields.fn011} $boolType,
          ${PackerFields.pm011} $boolType,
          ${PackerFields.bc011} $boolType,
          ${PackerFields.bn011} $boolType,
          ${PackerFields.bw011} $boolType,
          ${PackerFields.rb011} $boolType,
          ${PackerFields.ip1} $boolType,
          ${PackerFields.sc021} $boolType,
          ${PackerFields.bc021} $boolType,
          ${PackerFields.bd011} $boolType,
          ${PackerFields.tbc011} $boolType,
          ${PackerFields.lbc021} $boolType,
          ${PackerFields.tbc031} $boolType,
          ${PackerFields.lbc041} $boolType,
          ${PackerFields.tk1} $boolType,
          ${PackerFields.dr1} $boolType,

          ${PackerFields.sg012} $boolType,
          ${PackerFields.pg012} $boolType,
          ${PackerFields.as012} $boolType,
          ${PackerFields.as022} $boolType,
          ${PackerFields.bl2} $boolType,
          ${PackerFields.be01612} $boolType,
          ${PackerFields.as032} $boolType,
          ${PackerFields.pg022} $boolType,
          ${PackerFields.pg032} $boolType,
          ${PackerFields.bf2} $boolType,
          ${PackerFields.vs012} $boolType,
          ${PackerFields.be01662} $boolType,
          ${PackerFields.sc012} $boolType,
          ${PackerFields.bb2} $boolType,
          ${PackerFields.asb2} $boolType,
          ${PackerFields.la2} $boolType,
          ${PackerFields.b3b2} $boolType,
          ${PackerFields.bf012} $boolType,
          ${PackerFields.rf012} $boolType,
          ${PackerFields.sc032} $boolType,
          ${PackerFields.sc042} $boolType,
          ${PackerFields.as042} $boolType,
          ${PackerFields.fn012} $boolType,
          ${PackerFields.pm012} $boolType,
          ${PackerFields.bc012} $boolType,
          ${PackerFields.bn012} $boolType,
          ${PackerFields.bw012} $boolType,
          ${PackerFields.rb012} $boolType,
          ${PackerFields.ip2} $boolType,
          ${PackerFields.sc022} $boolType,
          ${PackerFields.bc022} $boolType,
          ${PackerFields.bd012} $boolType,
          ${PackerFields.tbc012} $boolType,
          ${PackerFields.lbc022} $boolType,
          ${PackerFields.tbc032} $boolType,
          ${PackerFields.lbc042} $boolType,
          ${PackerFields.tk2} $boolType,
          ${PackerFields.dr2} $boolType,

          ${PackerFields.sg013} $boolType,
          ${PackerFields.pg013} $boolType,
          ${PackerFields.as013} $boolType,
          ${PackerFields.as023} $boolType,
          ${PackerFields.bl3} $boolType,

          ${PackerFields.dessg011} $textType,
          ${PackerFields.despg011} $textType,
          ${PackerFields.desas011} $textType,
          ${PackerFields.desas021} $textType,
          ${PackerFields.desbl1} $textType,
          ${PackerFields.desbe01611} $textType,
          ${PackerFields.desas031} $textType,
          ${PackerFields.despg021} $textType,
          ${PackerFields.despg031} $textType,
          ${PackerFields.desbf1} $textType,
          ${PackerFields.desvs011} $textType,
          ${PackerFields.desbe01661} $textType,
          ${PackerFields.dessc011} $textType,
          ${PackerFields.desbb1} $textType,
          ${PackerFields.desasb1} $textType,
          ${PackerFields.desla1} $textType,
          ${PackerFields.desb3b1} $textType,
          ${PackerFields.desbf011} $textType,
          ${PackerFields.desrf011} $textType,
          ${PackerFields.dessc031} $textType,
          ${PackerFields.dessc041} $textType,
          ${PackerFields.desas041} $textType,
          ${PackerFields.desfn011} $textType,
          ${PackerFields.despm011} $textType,
          ${PackerFields.desbc011} $textType,
          ${PackerFields.desbn011} $textType,
          ${PackerFields.desbw011} $textType,
          ${PackerFields.desrb011} $textType,
          ${PackerFields.desip1} $textType,
          ${PackerFields.dessc021} $textType,
          ${PackerFields.desbc021} $textType,
          ${PackerFields.desbd011} $textType,
          ${PackerFields.destbc011} $textType,
          ${PackerFields.deslbc021} $textType,
          ${PackerFields.destbc031} $textType,
          ${PackerFields.deslbc041} $textType,
          ${PackerFields.destk1} $textType,
          ${PackerFields.desdr1} $textType,

            ${PackerFields.dessg012} $textType,
            ${PackerFields.despg012} $textType,
            ${PackerFields.desas012} $textType,
            ${PackerFields.desas022} $textType,
            ${PackerFields.desbl2} $textType,
            ${PackerFields.desbe01612} $textType,
            ${PackerFields.desas032} $textType,
            ${PackerFields.despg022} $textType,
            ${PackerFields.despg032} $textType,
            ${PackerFields.desbf2} $textType,
            ${PackerFields.desvs012} $textType,
            ${PackerFields.desbe01662} $textType,
            ${PackerFields.dessc012} $textType,
            ${PackerFields.desbb2} $textType,
            ${PackerFields.desasb2} $textType,
            ${PackerFields.desla2} $textType,
            ${PackerFields.desb3b2} $textType,
            ${PackerFields.desbf012} $textType,
            ${PackerFields.desrf012} $textType,
            ${PackerFields.dessc032} $textType,
            ${PackerFields.dessc042} $textType,
            ${PackerFields.desas042} $textType,
            ${PackerFields.desfn012} $textType,
            ${PackerFields.despm012} $textType,
            ${PackerFields.desbc012} $textType,
            ${PackerFields.desbn012} $textType,
            ${PackerFields.desbw012} $textType,
            ${PackerFields.desrb012} $textType,
            ${PackerFields.desip2} $textType,
            ${PackerFields.dessc022} $textType,
            ${PackerFields.desbc022} $textType,
            ${PackerFields.desbd012} $textType,
            ${PackerFields.destbc012} $textType,
            ${PackerFields.deslbc022} $textType,
            ${PackerFields.destbc032} $textType,
            ${PackerFields.deslbc042} $textType,
            ${PackerFields.destk2} $textType,
            ${PackerFields.desdr2} $textType,

              ${PackerFields.dessg013} $textType,
              ${PackerFields.despg013} $textType,
              ${PackerFields.desas013} $textType,
              ${PackerFields.desas023} $textType,
              ${PackerFields.desbl3} $textType
    )  
  ''');
}
