name: Inspection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.10.2 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  shared_preferences: ^0.5.4
  flutter_slidable: ^0.5.7
  path_provider: ^2.0.1
  open_file: ^3.1.0
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  http: ^0.13.3
  pdf: ^3.0.1
  get: ^4.1.4
  firebase_core: ^1.5.0
  cloud_firestore: ^2.4.0
  



dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/data/
    - assets/icons/
    - assets/images/
  fonts: 
    - family: Londrina
      fonts: 
        - asset: fonts/LondrinaSolid-Light.ttf
        - asset: fonts/LondrinaSolid-Regular.ttf
  uses-material-design: true

